### ISSUE TITLE
TODO: Post Category 연결 & 기타 작업 (ex. GET POST by Category)

### ISSUE THREAD

**Issue by ABizCho** [modulersYJ/ganoverflow-back#34]
0. 카테고리 사전 정의 및 ENTITIES 반영
1. chatposts POST로 올릴 때 category 드랍다운 메뉴로 설정할 수 있게 front/back 작업
2. DB 기존 데이터에 필드 추가 및 매뉴얼 필드밸류 수동 추가 작업

**Comment by hongregii** [comment]
PR 날렸읍니다.
PR 올려놓고 보니까 게시판 페이지에서 카테고리까지 JOIN 안돼서 온다는거 발견했네요 .. ㅋㅋㅋ 이건 MERGE 후에 HOTFIX 하는거로 할게요
