### ISSUE TITLE
FIXME : access_token 발급 시 유저 잘 찾는지 + 저장하는지 확인 필요

### ISSUE THREAD

**Issue by hongregii** [modulersYJ/ganoverflow-back#43]
# 댓글 작성을 하면, 다른 user가 join 돼서 Insert되는 문제 발생

- 댓글 작성시, authData로 GenerateHeaders 를 작동시켜 postComments 요청 보내고 있음
- authData는 useAuthDataHook을 써서 받아오는데, 이 훅은 sessionStorage에서 id을 찾아오는 듯함
- sessionStorage에는 id가 잘 들어가 있음 (로그인할때 id 잘 리턴해서 저장한듯)
- 그러면 Nest에서 AuthGuard가 request.user 를 등록할 때, 즉
   ``` typescript
     try {
      // refresh, access 모두 포함한 후보리스트에 대해 탐색
      const payload = this.jwtService.verify(token, {
        secret: jwtConstants.secret,
      });
      request.user = payload;
    } catch (err) {
      throw new UnauthorizedException("유효하지 않은 토큰입니다.");
    }
    return true;
    ```
    이부분에서 뭔가 이상한걸 저장한게 아닌가 싶음.

- **그런데 chatPost 저장할때는 잘 되는게 이상하긴 함 .. **

## 결론
access_token 관련 로직에서 jwt sign 하는부분 봐주세요! chatPost쪽 insert가 잘 작동되는걸 봐서는 Next 쪽에서 뭔가 이상하게 요청을 보내고 있을수도 있음

**Comment by ABizCho** [comment]
오호...요상구리하네요 이 문제는 내일중에 파악해보록 할게요!

**Comment by ABizCho** [comment]
authGuard를 타서 intercept된 request.user정보(payload)는 정상적인 유저id를 반환하고 있는걸 확인했어요! 이후 로직들 확인하면 될것같아요

**Comment by ABizCho** [comment]
커멘트 컨트롤러에서도 정상적인 req.user를 보여주고있어요

**Comment by ABizCho** [comment]
@hongregii 
문제 식별 완료 및 수정했습니다!

기존에는 아래의 컨트롤러에서     
`const user = await this.userService.findOneByUserName(req.user.username);`으로 작성돼있었는데,

저희 jwt토큰은 아래와 같이 `sub`라는 key로 `userId`만을 저장하고 있어요! 

```
{
  "iat": 1689876951,
  "exp": 1690481751,
  "sub": "02c160e4-d2f9-476c-9eaa-0bebc21f63cf"
}
```

따라서 아래와 같이 `sub=id`로 findOneById를 사용하도록 수정해줬습니다.

`const user = await this.userService.findOneById(req.user.sub);`

아마 findOneByUserName 함수가 타겟을 찾지 못했을 때 예외처리가 제대로 작성돼있지 않아서, 임의로 특정 유저를 찾아 처리해버리는 문제로 혼선이 있었던것 같습니다! 이는 추후 fix하면 될것같아요!


---

### RES MOD CODE

```ts
  @Post("/:chatPostId")
  async create(
    @Param("chatPostId")
    chatPostId: string,
    @Body() createCommentDto: CreateCommentDto,
    @Req() req
  ) {
    // console.log("commentController - create - chatPostId", chatPostId);
    console.log("comment controller reqUser!!!", req.user);
    const chatPost = await this.chatPostsService.findOne(chatPostId);
    const user = await this.userService.findOneById(req.user.sub);
    return this.commentsService.create(chatPost, user, createCommentDto);
  }
  ```

**Comment by ABizCho** [comment]
총 변경사항 (제 작업도 포함) 오늘 내로 PR 올리겠습니다!
