### ISSUE TITLE
Bug: 게시판(PLP) 내 게시물을 클릭했을 때,  서버 에러 식별

### ISSUE THREAD

**Issue by ABizCho** [modulersYJ/ganoverflow-back#49]
@hongregii 홍래님 버그 식별했습니다! 혹시 확인된 내용이면 공유 부탁드려요!

![image](https://github.com/modulersYJ/ganoverflow-back/assets/65459616/e917dda3-5045-4c36-95b2-e8da1883fd79)

**Comment by hongregii** [comment]
![image](https://github.com/modulersYJ/ganoverflow-back/assets/98505239/98069c6d-560f-43c1-a6ec-95bab4f1b287)

이거네요
일단 optional chaining 붙여놔서 hotfix 할게요 이부분은 JSON으로 바뀌면서 생긴 문제인듯 한데
성우님이 구조 봐주셔야 할것 같슴다
